; =====================================================
; GEMEINSAME EINSTELLUNGEN (Für S3 und C3)
; =====================================================
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

; =====================================================
; UMGEBUNG 1: DER COORDINATOR (ESP32-S3)
; =====================================================
[env:coordinator]
board = esp32-s3-devkitc-1
build_src_filter = +<coordinator/>

; Zwingt den ESP32 auf 16MB Flash und nutzt deine Tabelle
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

; Schaltet den 8MB PSRAM deines N16R8 Chips ein
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Alle benötigten Bibliotheken für den Webserver
lib_deps = 
    fastled/FastLED @ ^3.6.0
    mathieucarbou/ESPAsyncWebServer @ ^3.3.6
    mathieucarbou/AsyncTCP @ ^3.2.4
    bblanchon/ArduinoJson @ ^7.0.4


; =====================================================
; UMGEBUNG 2: DIE PUCKS (ESP32-C3)
; =====================================================
[env:puck]
board = lolin_c3_mini
build_src_filter = +<puck/>

lib_deps = 
    fastled/FastLED @ ^3.6.0

; Das Lolin C3 Mini nutzt den internen USB-Controller des C3 direkt für den Serial Monitor.
; Diese Flags sorgen dafür, dass "Serial.print" sofort über das USB-C Kabel funktioniert!
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1