; =====================================================
; GEMEINSAME EINSTELLUNGEN
; =====================================================
[env]
framework = arduino
monitor_speed = 115200

; =====================================================
; UMGEBUNG 1: DER COORDINATOR (ESP32-S3) -> NEUER CORE 3.x FÜR NATIVEN RSSI
; =====================================================
[env:coordinator]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
build_src_filter = +<coordinator/>

board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

build_flags = 
    -D PUCK_RACER_DEBUG
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps = 
    fastled/FastLED @ ^3.6.0
    mathieucarbou/ESPAsyncWebServer @ ^3.3.6
    mathieucarbou/AsyncTCP @ ^3.2.4
    bblanchon/ArduinoJson @ ^7.0.4

; =====================================================
; UMGEBUNG 2: DIE PUCKS (ESP32-C3) -> STABILER CORE 2.x (Kein RISC-V Download nötig)
; =====================================================
[env:puck]
platform = espressif32
board = esp32-c3-devkitm-1
build_src_filter = +<puck/>

lib_deps =
    fastled/FastLED @ ^3.6.0

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1